name: Email Action Example

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3001591@ds.study.iitm.ac.in
        run: echo "Hello, world!"
